name: "web_app"
mode: "dev"
port: 9090
version: "v1.0"

log:
  level: "debug"
  filename: "logs.log"
  max_size: 20
  max_age: 30
  max_backups: 10

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "mysql2022"
  dbname: "demo"
  dsn: "root:mysql2022@(127.0.0.1:3306)/demo?charset=utf8mb4&parseTime=True&loc=Local"
  max_open_conn: 200
  max_idle_conn: 50

redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  password: ""
  pool_size: 100
  min_idle_conn: 30